apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/webapp
patches:
  - path: deployment.yaml
    target:
      version: v1
      kind: Deployment
      name: webapp
  - path: ingress.yaml
    target:
      version: v1
      kind: Ingress
      name: webapp-ingress
