apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: webapp
data:
  # FIXME: 作成したRDSのエンドポイントに書き換えてください
  db.host: example-for-eks.cluster-chy2qs2ac087.ap-northeast-1.rds.amazonaws.com
  db.name: webapp_db
