apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp
  labels:
    app: webapp
spec:
  replicas: 2
  template:
    spec:
      serviceAccountName: webapp-sa
      containers:
        - name: webapp-php
          image: 783764615631.dkr.ecr.ap-northeast-1.amazonaws.com/webapp-php:v1.0.0
          imagePullPolicy: Always
          volumeMounts:
            # base の volumeMounts の値を上書きするので php-sock が消えないようにこちらでも定義する
            - name: php-sock
              mountPath: /var/run/php
            - name: secret-store
              mountPath: /var/secrets
              readOnly: true
        - name: webapp-nginx
          image: 783764615631.dkr.ecr.ap-northeast-1.amazonaws.com/webapp-nginx:v1.0.0
          imagePullPolicy: Always
      volumes:
        - name: secret-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              # 使用するSecretProviderClassの名前
              secretProviderClass: "webapp-secret-provider"
