apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: webapp
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy: {}
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      containers:
        - image: mysql:8.0
          name: mysql
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-pass
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: db.name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: pass
