apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: webapp
  labels:
    app: db
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: db
  type: ClusterIP
